// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Cashier struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Discount struct {
	ID              int32     `json:"id"`
	Qty             int32     `json:"qty"`
	Type            string    `json:"type"`
	Result          int32     `json:"result"`
	ExpiredAt       time.Time `json:"expired_at"`
	ExpiredAtFormat string    `json:"expired_at_format"`
	StringFormat    string    `json:"string_format"`
}

type Order struct {
	ID          int32     `json:"id"`
	CashierID   int32     `json:"cashier_id"`
	PaymentID   int32     `json:"payment_id"`
	TotalPrice  int32     `json:"total_price"`
	PricePaid   int32     `json:"price_paid"`
	TotalReturn int32     `json:"total_return"`
	ReceiptID   string    `json:"receipt_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OrderDetail struct {
	ID               int32         `json:"id"`
	ProductID        int32         `json:"product_id"`
	OrderID          int32         `json:"order_id"`
	ProductName      string        `json:"product_name"`
	DiscountID       sql.NullInt32 `json:"discount_id"`
	Qty              int32         `json:"qty"`
	Price            int32         `json:"price"`
	TotalFinalPrice  int64         `json:"total_final_price"`
	TotalNormalPrice int64         `json:"total_normal_price"`
}

type OrderProduct struct {
	ID        int32         `json:"id"`
	OrderID   sql.NullInt32 `json:"order_id"`
	ProductID sql.NullInt32 `json:"product_id"`
}

type Payment struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Logo      sql.NullString `json:"logo"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Product struct {
	ID         int32     `json:"id"`
	Sku        string    `json:"sku"`
	Name       string    `json:"name"`
	Stock      int32     `json:"stock"`
	Price      int32     `json:"price"`
	ImageUrl   string    `json:"image_url"`
	CategoryID int32     `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ProductDiscount struct {
	ID         int32 `json:"id"`
	DiscountID int32 `json:"discount_id"`
	ProductID  int32 `json:"product_id"`
}

type Sold struct {
	ID          int32  `json:"id"`
	ProductID   int32  `json:"product_id"`
	ProductName string `json:"product_name"`
	TotalQty    int32  `json:"total_qty"`
	TotalAmount int64  `json:"total_amount"`
}
