// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: payment.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO payments (
    name, type, logo
) VALUES (
    ?,?,?
)
`

type CreatePaymentParams struct {
	Name string         `json:"name"`
	Type string         `json:"type"`
	Logo sql.NullString `json:"logo"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment, arg.Name, arg.Type, arg.Logo)
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments
WHERE id = ?
`

func (q *Queries) DeletePayment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, name, type, logo, created_at, updated_at FROM payments
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, name, type, logo, created_at, updated_at FROM payments
ORDER BY id LIMIT ? OFFSET ?
`

type ListPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Logo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE payments SET name = ?,type=?,logo=?,updated_at=CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePaymentParams struct {
	Name string         `json:"name"`
	Type string         `json:"type"`
	Logo sql.NullString `json:"logo"`
	ID   int32          `json:"id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, updatePayment,
		arg.Name,
		arg.Type,
		arg.Logo,
		arg.ID,
	)
	return err
}
