// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCashier(ctx context.Context, arg CreateCashierParams) (sql.Result, error)
	CreateCategory(ctx context.Context, name string) (sql.Result, error)
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) (sql.Result, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreateOrderDetails(ctx context.Context, arg CreateOrderDetailsParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	CreateProductDiscount(ctx context.Context, arg CreateProductDiscountParams) error
	DeleteCashier(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeletePayment(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DetailCashier(ctx context.Context, id int32) (Cashier, error)
	GetCashier(ctx context.Context, id int32) (GetCashierRow, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetDiscount(ctx context.Context, id int32) (Discount, error)
	GetOrderDetails(ctx context.Context, id int32) ([]GetOrderDetailsRow, error)
	GetPayment(ctx context.Context, id int32) (Payment, error)
	GetProduct(ctx context.Context, id int32) (Product, error)
	GetProductDetails(ctx context.Context, id int32) (GetProductDetailsRow, error)
	GetRevenue(ctx context.Context) ([]GetRevenueRow, error)
	GetSold(ctx context.Context) ([]GetSoldRow, error)
	InsertSold(ctx context.Context, arg InsertSoldParams) error
	ListAllOrderDetails(ctx context.Context, arg ListAllOrderDetailsParams) ([]ListAllOrderDetailsRow, error)
	ListCashiers(ctx context.Context, arg ListCashiersParams) ([]Cashier, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsDetailsByCategoryID(ctx context.Context, arg ListProductsDetailsByCategoryIDParams) ([]ListProductsDetailsByCategoryIDRow, error)
	ListProductsDetailsByName(ctx context.Context, arg ListProductsDetailsByNameParams) ([]ListProductsDetailsByNameRow, error)
	UpdateCashier(ctx context.Context, arg UpdateCashierParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
